#!/usr/bin/env bash

set -e

function findEnvConfig() {
  wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 -o /dev/null -O ~/yq
  chmod +x ~/yq
  ~/yq r /app/config.yml ":${MAGMA_ENV:development}"
}

if [ "${MAGMA_ENV}" == "test" ]; then
PGPASSWORD=password psql -h magma_db -U developer -d magma_development -c "DROP DATABASE magma_test;"
PGPASSWORD=password psql -h magma_db -U developer -d magma_development -c "CREATE DATABASE magma_test;"
PGPASSWORD=password psql -h magma_db -U developer -d magma_development -c "GRANT ALL PRIVILEGES ON DATABASE magma_test TO developer;"
else
MAGMA_ENV=test $0
fi

# TODO: Replace this with project model scripts.
if [ -n "$UPDATE_STATE" ]; then
  bin/magma global_migrate

  for project in $(findEnvConfig | grep ':project_path:' | sed -e 's/.*:project_path:\s*//g'); do
    echo "Initializing $project..."
    bin/magma create_schema "$(basename $project)" || true
    bin/magma create_db "$(basename $project)" || true
  done

  bin/magma migrate || true
fi
