version: '3.4'
volumes:
  magma-app-gems:
    driver: local
  magma-db-data:
    driver: local
  magma-log-dir:
    driver: local
  magma-tmp-dir:
    driver: local

networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'

x-magma_base: &magma_base
  build:
    context: .
    dockerfile: docker/app/Dockerfile.development
  image: magma_base
  volumes:
    - .:/app:cached
    - magma-app-gems:/app/vendor/bundle:rw
    - magma-log-dir:/app/log:rw
    - magma-tmp-dir:/app/tmp:rw
    - ./projects:/app/projects
    - ../etna:/etna:cached
  environment: &app_environment
    COVERAGE: 'true'
    DATABASE_HOST: 'magma_db'
    MAGMA_ENV: 'development'
    MASTER_BUILD: '${MASTER_BUILD}'
  # Maps external facing host names to the internal ip for development-apache.
  extra_hosts:
    - 'metis.development.local:172.16.238.10'
  networks:
    edge_net:
    default:

services:
  magma_app:
    <<: *magma_base
    ports:
      - 3003:3000
    command: ./docker/app/puma.sh
    depends_on:
      - magma_db

  magma_db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - magma-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: magma_development
      POSTGRES_PASSWORD: password
      POSTGRES_USER: developer
    ports:
      - 5432
    container_name: magma_db_1
