
version: '3.4'

x-base-etna-service:
  &base-etna-service # Base configuration used by most etna services.
  image: etna-base-dev
  volumes: &base-etna-service-volumes
    - .:/app:delegated
    - magma-app-gems:/app/vendor/bundle:rw
    - magma-log-dir:/app/log:rw
    - magma-tmp-dir:/app/tmp:rw
    - magma-public-dir:/app/public:rw
    - magma-data-dir:/app/data:rw
    - magma-opt-dir:/usr/opt:rw
    - magma-node-modules:/app/node_modules
    - ../etna:/etna:delegated
  environment: &base-etna-env
    'MAGMA_ENV': 'development'
    APP_NAME: 'magma'
  entrypoint: /entrypoints/development.sh

  networks:
    default:
    edge_net:
  extra_hosts:
    - 'metis.development.local:172.16.238.10'
    - 'magma.development.local:172.16.238.10'
    - 'janus.development.local:172.16.238.10'
    - 'timur.development.local:172.16.238.10'
    - 'rtemis.development.local:172.16.238.10'
    - 'archimedes.development.local:172.16.238.10'
    - 'polyphemus.development.local:172.16.238.10'

x-base-etna-services:
  &base-etna-services # Default list of services an etna app may have.
  'magma_app': &base-etna-app # The ruby webserver
    <<: *base-etna-service
    command: ./bin/puma.sh
    depends_on:
      - 'magma_db'

  'magma_webpack':
    &base-etna-webpack # The ruby webpack server watching for changes
    <<: *base-etna-service
    command: npm run webpack

  'magma_db':
    &base-etna-db # The application specific database.  Overwrite with development-psql-9 to use psql 9 instead.
    image: development-psql
    volumes:
      - magma-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'magma_development'
      POSTGRES_PASSWORD: password
      POSTGRES_USER: developer
      APP_NAME: 'magma'
    container_name: 'magma_db_1'

  'magma_app_fe':
    &base-etna-fe # The application level apache frontend serving static assets, data, and proxying the main app.
    image: etna-apache
    volumes:
      - magma-public-dir:/app/public:ro
    depends_on:
      - 'magma_app'
    command: ['httpd', '-DFOREGROUND']
    entrypoint: /entrypoints/development_app_fe.sh
    environment:
      APP_NAME: 'magma_app_fe'

networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'

volumes:
  magma-app-gems:
    driver: local
  magma-db-data:
    driver: local
    name: "magma-db-data"
  magma-log-dir:
    driver: local
    name: "magma-log-dir"
  magma-tmp-dir:
    driver: local
    name: "magma-tmp-dir"
  magma-public-dir:
    driver: local
    name: "magma-public-dir"
  magma-data-dir:
    driver: local
    name: "magma-data-dir"
  magma-opt-dir:
    driver: local
  magma-node-modules:
    driver: local
    name: "magma-node-modules"

services:
  <<: *base-etna-services
  "magma_webpack":
    image: alpine
    # Magma does not really have a webpack setup
    command: echo 1

