source 'http://rubygems.org'

gem 'rack'
gem 'pg'
gem 'sequel'
gem 'mini_magick'
gem 'germ'
gem 'net-http-persistent'
gem 'extlib'
gem 'carrierwave-sequel'
gem 'activesupport', '>= 4.2.6'
gem 'fog'
gem 'spreadsheet'
gem 'pry'
