require_relative 'models/ipi'
require_relative 'models/patient'
require_relative 'models/clinical'
require_relative 'models/experiment'
require_relative 'models/project'
require_relative 'models/document'
require_relative 'models/gene_exp'
require_relative 'models/imaging'
require_relative 'models/rnaseq_batch'
require_relative 'models/rna_seq_qc'
require_relative 'models/rna_seq'
require_relative 'models/samples'
require_relative 'models/population'
require_relative 'models/mfi'

require_relative 'loaders/flow_jo'
require_relative 'loaders/clinical_colorectal'
