Sequel.migration do
  change do
    create_table(:clinical_breasts) do
      primary_key :id
      DateTime :created_at
      DateTime :updated_at
      String :clinical_name
      unique :clinical_name
      Integer :age_at_diagnosis
      String :sex
      String :race_ethnicity
      String :treatment
      String :stage
      String :grade
      String :outcomes
      String :history
    end
    create_table(:clinical_hnscs) do
      primary_key :id
      DateTime :created_at
      DateTime :updated_at
      String :clinical_name
      unique :clinical_name
      Integer :age_at_diagnosis
      String :sex
      String :race_ethnicity
      String :treatment
      String :stage
      String :grade
      String :outcomes
      String :history
      String :site
      TrueClass :hpv
      String :biopsy
    end
    create_table(:clinical_melanomas) do
      primary_key :id
      DateTime :created_at
      DateTime :updated_at
      String :clinical_name
      unique :clinical_name
      Integer :age_at_diagnosis
      String :sex
      String :race_ethnicity
      String :treatment
      String :stage
      String :grade
      String :outcomes
      String :history
      String :site
      String :ecog
      String :histology
      String :oncogene_status
      String :ldh
      String :metastatic_sites
      String :biopsy
    end
    create_table(:clinical_colorectals) do
      primary_key :id
      DateTime :created_at
      DateTime :updated_at
      String :clinical_name
      unique :clinical_name
      Integer :age_at_diagnosis
      String :sex
      String :race_ethnicity
      String :treatment
      String :stage
      String :grade
      String :outcomes
      String :history
      String :site
      String :histology
      Float :lymph_fraction
      String :msi_status
      String :oncogene_status
    end
  end
end
