name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Setup deps and run RSpec test suite
      env:
        PGHOST: 127.0.0.1
        PGUSER: developer
        MAGMA_ENV: test
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
        cp config.yml.test config.yml
        bin/magma create_db labors
        bin/magma migrate
        bin/magma global_migrate
        rspec spec/
